# Generated by Django 6.0.7 on 2026-08-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_payment_link_payment_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, default='unpaid', max_length=50, null=True, verbose_name='Статус оплаты Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, default='open', max_length=50, null=True, verbose_name='Статус сессии Stripe'),
        ),
    ]
